"""initial_schema

Revision ID: b2b119342aff
Revises: 
Create Date: 2026-05-23 06:55:21.343396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b119342aff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_events_id'), 'ab_events', ['id'], unique=False)
    op.create_table('failure_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fusion_id', sa.Integer(), nullable=True),
    sa.Column('profession', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_records_id'), 'failure_records', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('inspirations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('spark', sa.Text(), nullable=True),
    sa.Column('fragment_count', sa.Integer(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspirations_id'), 'inspirations', ['id'], unique=False)
    op.create_index(op.f('ix_inspirations_user_id'), 'inspirations', ['user_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompts', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('onboarded', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('tier', sa.String(length=20), server_default='free', nullable=True),
    sa.Column('trial_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('co_creations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_a_name', sa.String(length=100), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('user_b_name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('potential_score', sa.Integer(), nullable=True),
    sa.Column('complement_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_creations_id'), 'co_creations', ['id'], unique=False)
    op.create_index(op.f('ix_co_creations_user_a_id'), 'co_creations', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_co_creations_user_b_id'), 'co_creations', ['user_b_id'], unique=False)
    op.create_table('fusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('fragment_ids', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('feedback', sa.String(length=20), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_reason', sa.Text(), nullable=True),
    sa.Column('feedback_source', sa.String(length=20), nullable=True),
    sa.Column('needs_review', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusions_id'), 'fusions', ['id'], unique=False)
    op.create_index(op.f('ix_fusions_user_id'), 'fusions', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('suggested_fragments', sa.Text(), nullable=True),
    sa.Column('extracted_fragment_ids', sa.String(length=500), nullable=True),
    sa.Column('auto_extracted_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('fusion_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('is_new_record', sa.Integer(), nullable=True),
    sa.Column('followup_question', sa.Text(), nullable=True),
    sa.Column('followup_answer', sa.Text(), nullable=True),
    sa.Column('followup_fragments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fusion_id'], ['fusions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_fusion_id'), 'checkins', ['fusion_id'], unique=False)
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('co_creation_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co_creation_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('initiator_name', sa.String(length=100), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cool_down_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_available', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('paid_by', sa.String(length=10), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('map_generated', sa.Boolean(), nullable=True),
    sa.Column('map_id', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archive_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['co_creation_id'], ['co_creations.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_creation_orders_co_creation_id'), 'co_creation_orders', ['co_creation_id'], unique=False)
    op.create_index(op.f('ix_co_creation_orders_id'), 'co_creation_orders', ['id'], unique=False)
    op.create_index(op.f('ix_co_creation_orders_initiator_id'), 'co_creation_orders', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_co_creation_orders_partner_id'), 'co_creation_orders', ['partner_id'], unique=False)
    op.create_table('fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('fragment_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('archived', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragments_id'), 'fragments', ['id'], unique=False)
    op.create_index(op.f('ix_fragments_journal_id'), 'fragments', ['journal_id'], unique=False)
    op.create_index(op.f('ix_fragments_user_id'), 'fragments', ['user_id'], unique=False)
    op.create_table('fusion_diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fusion_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fusion_id'], ['fusions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fusion_diaries_fusion_id'), 'fusion_diaries', ['fusion_id'], unique=False)
    op.create_index(op.f('ix_fusion_diaries_id'), 'fusion_diaries', ['id'], unique=False)
    op.create_index(op.f('ix_fusion_diaries_user_id'), 'fusion_diaries', ['user_id'], unique=False)
    op.create_table('journey_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fusion_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('time_to_result', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fusion_id'], ['fusions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journey_maps_fusion_id'), 'journey_maps', ['fusion_id'], unique=False)
    op.create_index(op.f('ix_journey_maps_id'), 'journey_maps', ['id'], unique=False)
    op.create_index(op.f('ix_journey_maps_user_id'), 'journey_maps', ['user_id'], unique=False)
    op.create_table('co_creation_fragments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co_creation_id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['co_creation_id'], ['co_creations.id'], ),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_creation_fragments_fragment_id'), 'co_creation_fragments', ['fragment_id'], unique=False)
    op.create_index(op.f('ix_co_creation_fragments_id'), 'co_creation_fragments', ['id'], unique=False)
    op.create_table('map_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('overall_progress', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['journey_maps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_progress_id'), 'map_progress', ['id'], unique=False)
    op.create_index(op.f('ix_map_progress_map_id'), 'map_progress', ['map_id'], unique=False)
    op.create_index(op.f('ix_map_progress_user_id'), 'map_progress', ['user_id'], unique=False)
    op.create_table('map_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=50), nullable=True),
    sa.Column('landmark_icon', sa.String(length=10), nullable=True),
    sa.Column('time_estimate', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['journey_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_steps_id'), 'map_steps', ['id'], unique=False)
    op.create_index(op.f('ix_map_steps_map_id'), 'map_steps', ['map_id'], unique=False)
    op.create_table('micro_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('growth_stage', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_checkin_date', sa.String(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_micro_habits_fragment_id'), 'micro_habits', ['fragment_id'], unique=False)
    op.create_index(op.f('ix_micro_habits_id'), 'micro_habits', ['id'], unique=False)
    op.create_index(op.f('ix_micro_habits_user_id'), 'micro_habits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_micro_habits_user_id'), table_name='micro_habits')
    op.drop_index(op.f('ix_micro_habits_id'), table_name='micro_habits')
    op.drop_index(op.f('ix_micro_habits_fragment_id'), table_name='micro_habits')
    op.drop_table('micro_habits')
    op.drop_index(op.f('ix_map_steps_map_id'), table_name='map_steps')
    op.drop_index(op.f('ix_map_steps_id'), table_name='map_steps')
    op.drop_table('map_steps')
    op.drop_index(op.f('ix_map_progress_user_id'), table_name='map_progress')
    op.drop_index(op.f('ix_map_progress_map_id'), table_name='map_progress')
    op.drop_index(op.f('ix_map_progress_id'), table_name='map_progress')
    op.drop_table('map_progress')
    op.drop_index(op.f('ix_co_creation_fragments_id'), table_name='co_creation_fragments')
    op.drop_index(op.f('ix_co_creation_fragments_fragment_id'), table_name='co_creation_fragments')
    op.drop_table('co_creation_fragments')
    op.drop_index(op.f('ix_journey_maps_user_id'), table_name='journey_maps')
    op.drop_index(op.f('ix_journey_maps_id'), table_name='journey_maps')
    op.drop_index(op.f('ix_journey_maps_fusion_id'), table_name='journey_maps')
    op.drop_table('journey_maps')
    op.drop_index(op.f('ix_fusion_diaries_user_id'), table_name='fusion_diaries')
    op.drop_index(op.f('ix_fusion_diaries_id'), table_name='fusion_diaries')
    op.drop_index(op.f('ix_fusion_diaries_fusion_id'), table_name='fusion_diaries')
    op.drop_table('fusion_diaries')
    op.drop_index(op.f('ix_fragments_user_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_journal_id'), table_name='fragments')
    op.drop_index(op.f('ix_fragments_id'), table_name='fragments')
    op.drop_table('fragments')
    op.drop_index(op.f('ix_co_creation_orders_partner_id'), table_name='co_creation_orders')
    op.drop_index(op.f('ix_co_creation_orders_initiator_id'), table_name='co_creation_orders')
    op.drop_index(op.f('ix_co_creation_orders_id'), table_name='co_creation_orders')
    op.drop_index(op.f('ix_co_creation_orders_co_creation_id'), table_name='co_creation_orders')
    op.drop_table('co_creation_orders')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_fusion_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_fusions_user_id'), table_name='fusions')
    op.drop_index(op.f('ix_fusions_id'), table_name='fusions')
    op.drop_table('fusions')
    op.drop_index(op.f('ix_co_creations_user_b_id'), table_name='co_creations')
    op.drop_index(op.f('ix_co_creations_user_a_id'), table_name='co_creations')
    op.drop_index(op.f('ix_co_creations_id'), table_name='co_creations')
    op.drop_table('co_creations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_inspirations_user_id'), table_name='inspirations')
    op.drop_index(op.f('ix_inspirations_id'), table_name='inspirations')
    op.drop_table('inspirations')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_failure_records_id'), table_name='failure_records')
    op.drop_table('failure_records')
    op.drop_index(op.f('ix_ab_events_id'), table_name='ab_events')
    op.drop_table('ab_events')
    # ### end Alembic commands ###
